MASTER_PASSWORD = "ILOVEAAP"
SECRET_KEY = "JBSWY3DPEHPK3PXP"

[supabase]
url = "https://wqdfkzazckdstlxuoazl.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxZGZremF6Y2tkc3RseHVvYXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjA5MzAsImV4cCI6MjA3MDk5NjkzMH0.kVj9JJtiQcaFhZx9ix-hGvV1ImquPtBRsvmzgOj0zoA"   

[gemini]
api_key = "AIzaSyAZmfZt3g-Cv89TnC7UTrU4yP-jlxw2lS0"       

[googlemaps]
api_key = "AIzaSyCcHZDjfgvgsDgPFY57kkx095gvESfX5CM"   # enable Distance Matrix API

[routing]
country_name = "United States"
country_code = "us"
